export const PacketIds = {
	SERVER_ALIVE: 0,
	SERVER_GET_PLAYERS: 1,
	SERVER_GET_ALL_PLAYERS: 2,
	SERVER_POST_PLAYERS: 3,
	SERVER_GET_STATUS: 4,
	SERVER_SET_STATUS: 5,
	SERVER_WHITELIST: 6,
	SERVER_ANNOUNCEMENT: 7,
	SERVER_COMMAND: 8,

	SERVER_SUB_UPDATE: 15,

	STAFF_CHAT: 20,
	STAFF_BAN: 21,
	STAFF_BAN_IP: 22,
	STAFF_BAN_DEVICE: 23,
	STAFF_MUTE: 24,
	STAFF_WARN: 25,
	STAFF_ANTICHEAT_NOTICE: 26,
	STAFF_COMMAND_SEE: 27,

	PLAYER_MESSAGE: 40,
	PLAYER_TRANSFER: 41,
	PLAYER_TRANSFER_COMPLETE: 42,
	PLAYER_CONNECT: 43,
	PLAYER_DISCONNECT: 44,
	PLAYER_SUMMON: 45,
	PLAYER_CHAT: 46,
	PLAYER_TELL: 47,
	PLAYER_SESSION_SAVED: 48,
	PLAYER_RECONNECT: 49,
	PLAYER_LOAD_ACTION: 50,
	PLAYER_DATA_TRANSFER: 51,

	DATA_SYNC: 60
};